# Generated by Django 4.0.2 on 2022-02-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.CharField(max_length=50),
        ),
    ]
